<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Proyectos\Proyecto;
use App\Models\Comercial\Cliente;
use App\Models\Lugar;
use App\Models\User;

class Ofertas2026Seeder extends Seeder
{
    public function run(): void
    {
        // ── Helpers ────────────────────────────────────────────────────────────────
        $cli = fn(string $alias)  => Cliente::where('alias', $alias)->value('id');
        $usr = fn(?string $nombre) => $nombre ? User::where('name', $nombre)->value('id') : null;
        $lug = fn(?string $nombre) => $nombre ? Lugar::where('nombre', $nombre)->value('id') : null;

        // ── Datos del CSV — mapeo columna a columna ────────────────────────────────
        // CP            → cp_numero
        // CLIENTE       → cliente_alias  (→ cliente_id via alias)
        // CONTACTO      → contacto       (solo nombre de la persona)
        // DATOS CONTACTO→ datos_contacto (teléfono + correo)
        // LUGAR         → lugar          (→ lugar_id via nombre)
        // ALCANCE       → alcance
        // OFERTA        → dn_numero (código técnico de la oferta)
        // FECHA ENVÍO   → fecha_envio
        // FECHA MOD.    → fecha_modificacion_oferta
        // OFERTAS EMIT. → monto_usd
        // HITOS DE PAGO → hitos_pago
        // RESPONSABLE   → elaboro_id     (→ user_id via name)
        // STATUS        → estado         (ENVIADO → 'presentado')
        // OFERTA (PDF)  → archivo_oferta
        // % ADJUDICACIÓN→ ponderacion    (10=REMOTO, 25=POSIBLE, 75=PROBABLE, 100=CONTRATADO)
        //
        // NOTA: CONCEPTO ADJUDICACIÓN y Cartera Esperada son derivados (no se almacenan).
        // NOTA: cp_numero null = sin CP asignado ("-" o "N/A" en el CSV).
        // NOTA: cp 016/26 aparece duplicado; el segundo (IGASAMEX-Luis Antonio) se guarda como '016-B/26'.
        $ofertas = [
            [
                'cp_numero'                 => '152/25',
                'cliente_alias'             => 'IGA',
                'contacto'                  => 'Anayeli Arenas',
                'datos_contacto'            => "Correo: aarenas@igasamex.com.mx",
                'lugar'                     => 'Veracruz',
                'alcance'                   => 'Suministro de accesorio para interconexion HT 30"x 4\' 600# Veracruz',
                'tech_reference'            => '251006-0-IGA-HTS 30x4 _Interconexion 30x4 600# Oleofinos',
                'fecha_envio'               => '2025-11-18',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 36566.26,
                'hitos_pago'                => "50% anticipo\n50% contra entrega de materiales",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '251006-0-IGA-HTS 30x4 _Interconexion 30x4 600# Oleofinos.pdf',
                'ponderacion'               => 75,
            ],
            [
                'cp_numero'                 => '157/25',
                'cliente_alias'             => 'ENG',
                'contacto'                  => 'Berenice Hernandez',
                'datos_contacto'            => "Correo: berenice.hernandez_eleno@engie.com",
                'lugar'                     => 'San Luis Potosi',
                'alcance'                   => 'Interconexión 42"x24" VDR (No Vinculante)',
                'tech_reference'            => '251027-1-ENG-HTP 42x24 _VDR',
                'fecha_envio'               => '2026-02-23',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 933232.40,
                'hitos_pago'                => "25% Anticipo\n25% Contra término de Excavación\n25% Contra Aviso de Movilización de Personal y Técnicos\n15% Al finalizar los Trabajos de Hot Tapping\n10% Contra aceptación del Libro de Proyecto",
                'responsable'               => 'Kevin Pérez',
                'archivo_oferta'            => '251027-2-ENG-HTP 42x24 _VDR.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => '001/26',
                'cliente_alias'             => 'PIR',
                'contacto'                  => 'Sergio Flores',
                'datos_contacto'            => "Correo: s.flores@pirsystem.com.mx",
                'lugar'                     => 'Chiapas',
                'alcance'                   => "Interconexión HT 30\"x 20' 150# Cactus, Reforma Chiapas",
                'tech_reference'            => "260106-0-AEP-HTS 30x20 _HT 30x 20' 150# Catus",
                'fecha_envio'               => '2026-01-14',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 103000.00,
                'hitos_pago'                => "40% anticipo\n40% contra movilización\n20% al término de actividades",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => "260106-0-AEP-HTS 30x20 _HT 30x 20' 150# Catus.pdf",
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => '002/26',
                'cliente_alias'             => 'NAT',
                'contacto'                  => 'Laura Marulanda',
                'datos_contacto'            => "Correo: compras_mexico4@naturgy.com",
                'lugar'                     => 'Mexico',
                'alcance'                   => 'Suministro anillos separadores y cierres elásticos',
                'tech_reference'            => '260126-0-NAT-VRS Suministro anillos separadores Naturgy',
                'fecha_envio'               => '2026-01-26',
                'fecha_modificacion_oferta' => '2026-02-17',
                'monto_usd'                 => 63500.00,
                'hitos_pago'                => 'Contra entrega de materiales (crédito a 30 días) 100%',
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260126-0-NAT-VRS Suministro anillos separadores Naturgy Rev.3.pdf',
                'ponderacion'               => 100,
            ],
            [
                'cp_numero'                 => '003/26',
                'cliente_alias'             => 'IGA',
                'contacto'                  => 'Dulce María Manzo Peña',
                'datos_contacto'            => "Correo: dmanzop@igasamex.com.mx",
                'lugar'                     => 'CDMX',
                'alcance'                   => 'Suministro Válvulas de compuerta Plana Slab Gate diferentes diámetros',
                'tech_reference'            => '260122-0-IGA-VLV VRSx _Suministro de VCP Dif. Diametros',
                'fecha_envio'               => '2026-01-22',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 29153.82,
                'hitos_pago'                => "50% Anticipo\n50% Contra entrega de material considerando 30 días para realizar el pago correspondiente",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260122-0-IGA-VLV VRSx _Suministro de VCP Dif. diametros.pdf',
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => '004/26',
                'cliente_alias'             => 'PTX',
                'contacto'                  => 'Alan Hernandez Cámara',
                'datos_contacto'            => "Correo: alan.hernandez@protexa.mx",
                'lugar'                     => 'Cd. Del Carmen',
                'alcance'                   => 'Suministro Válvulas Proyecto Cluster 2-SEJKAN',
                'tech_reference'            => '260205-0-PTX-VLV x _Suministro Válvulas Proyecto Cluster 2-SEJKAN',
                'fecha_envio'               => '2026-02-05',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 1721419.33,
                'hitos_pago'                => "50% Anticipo\n50% Contra entrega de válvulas",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260205-0-PTX-VLV x _Suministro Válvulas Proyecto Cluster 2-SEJKAN.pdf',
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => '005/26',
                'cliente_alias'             => 'EIN',
                'contacto'                  => 'Osvaldo Ugalde',
                'datos_contacto'            => "Correo: osvaldo.ugalde@euroinova.com",
                'lugar'                     => 'Hidalgo',
                'alcance'                   => 'Servicio DLS 6" 600# con Bypass 6\' Hidalgo',
                'tech_reference'            => '260127-0-EIN-DLSS 6x6 _Servicio DLS 6" 600#',
                'fecha_envio'               => '2026-01-28',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 121161.68,
                'hitos_pago'                => "30% Anticipo\n40% Contra movilización\n30% Finalizando la obturación",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260127-0-EIN-DLSS 6x6 _Servicio DLS 6 600#.pdf',
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => '016/26',          // Primer registro con este CP (MOLPER)
                'cliente_alias'             => 'MOL',
                'contacto'                  => 'Vicente Maravilla Flores',
                'datos_contacto'            => "Correo: hgo_13@hotmail.com",
                'lugar'                     => 'Hidalgo',
                'alcance'                   => 'Servicio DLS 6" 600# con Bypass 6\' Hidalgo',
                'tech_reference'            => '260127-1-EIN-DLSS 6x6 _Servicio DLS 6 Rev1',
                'fecha_envio'               => '2026-01-28',
                'fecha_modificacion_oferta' => '2026-02-11',
                'monto_usd'                 => 2976740.60,
                'hitos_pago'                => "30% Anticipo\n30% Contra entrega de accesorios soldables y tubería\n30% Contra movilización\n20% Al finalizar los servicios",
                'responsable'               => 'Aquiles Garcia',
                'archivo_oferta'            => 'propuesta dls 6 600 Rev 1 Hidlgo.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => '006/26',
                'cliente_alias'             => 'SRP',
                'contacto'                  => 'Diego Lievano',
                'datos_contacto'            => "Correo: buceo@serport.co",
                'lugar'                     => 'Colombia',
                'alcance'                   => "Proyecto de Hot Tapping 24\"x16\" Submarino - SERPORT (-19 m)",
                'tech_reference'            => '250128-0-SER-HTP 24x16 _HTP 24"x16" SUBMARINO',
                'fecha_envio'               => '2026-01-29',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 351900.00,
                'hitos_pago'                => "30% Anticipo\n40% Contra aviso de movilización\n30% Crédito a 30 días, después de terminado el servicio",
                'responsable'               => 'Sergio Ordaz',
                'archivo_oferta'            => '250128-0-SER-HTP 24x16 _HTP 24x16 SUBMARINO.pdf',
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => '007/26',
                'cliente_alias'             => 'GCI',
                'contacto'                  => 'Martha Ramírez Arriaga',
                'datos_contacto'            => null,
                'lugar'                     => 'Hidalgo',
                'alcance'                   => "Servicio de HT 8\" x 8\" 300# RF",
                'tech_reference'            => '260122-0-GCI-HTS 8x8 _TIE IN TP550-0091 Hot Tap 8 Nafta',
                'fecha_envio'               => '2026-01-28',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 9004.00,
                'hitos_pago'                => "50% Anticipo\n50% Al finalizar el servicio de perforación",
                'responsable'               => 'Diego Renato',
                'archivo_oferta'            => '260122-0-GCI-HTS 8x8 _TIE IN TP550-0091  Hot Tap 8 Nafta.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => '008/26',
                'cliente_alias'             => 'ICA',
                'contacto'                  => 'Felipe Aguirre / Antonio Rodríguez',
                'datos_contacto'            => "Correo: felipe.aguirre@ica.mx",
                'lugar'                     => 'Edo. Mexico',
                'alcance'                   => 'Desvío ac 24" av. 16 de septiembre',
                'tech_reference'            => '260122-0-ICA-HTSF 24x24 _Macro libramiento 16 de sep Naucalpan',
                'fecha_envio'               => '2026-01-28',
                'fecha_modificacion_oferta' => '2026-03-17',
                'monto_usd'                 => 1602421.09,
                'hitos_pago'                => "10% Anticipo\n15% Contra firma de ingeniería\n20% Contra 10 semana de fabricación y procura realizada\n15% Contra aviso de término de fabricación y suministros\n20% Contra aviso de movilización\n20% Contra término de los trabajos",
                'responsable'               => 'Diego Renato',
                'archivo_oferta'            => '260122-2-ICA-HTSF 24x24 _Macro libramiento 16 de sep Naucalpan. Rev.02.pdf',
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => '009/26',
                'cliente_alias'             => 'SIC',
                'contacto'                  => 'José Perez',
                'datos_contacto'            => "Correo: j.perez@sicim.eu",
                'lugar'                     => 'Aguascalientes',
                'alcance'                   => 'Servicios HT 30"x20 600# EMRyC Aguascalientes',
                'tech_reference'            => '260203-0-SIC-HTSF 30x20 _Servicios Hot Tap 30x20 600#',
                'fecha_envio'               => '2026-02-04',
                'fecha_modificacion_oferta' => '2026-02-09',
                'monto_usd'                 => 256170.47,
                'hitos_pago'                => "50% Anticipo\n50% Finalizando la perforación en sitio",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260203-0-SIC-HTSF 30x20 _Servicios Hot Tap 30x20 600# Rev.1.pdf',
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => '010/26',
                'cliente_alias'             => 'COP',
                'contacto'                  => 'Cecilio Osvaldo Peña Corona',
                'datos_contacto'            => "Correo: felipe.aguirre@ica.mx",
                'lugar'                     => 'Edo. Mexico',
                'alcance'                   => 'Suministro Juntas dieléctricas',
                'tech_reference'            => '260130-0-COP-OTH x _Suministro Juntas Dielectricas',
                'fecha_envio'               => '2026-01-30',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 5000.00,
                'hitos_pago'                => "50% Anticipo\n50% Contra entrega materiales",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260130-0-COP-OTH x _Suministro Juntas Dielectricas.pdf',
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => null,          // N/A en CSV
                'cliente_alias'             => 'IGC',
                'contacto'                  => 'Ing. Marisela Noverola',
                'datos_contacto'            => "Correo: mnoverolaindheca@outlook.com",
                'lugar'                     => 'Tabasco',
                'alcance'                   => 'Separador Horizontal de Gas de Desfogue — FA-700 para campo BAKTE',
                'tech_reference'            => '260205-0-IGC-P&C x _Separador Horizontal de Gas de Desfogues',
                'fecha_envio'               => '2026-02-05',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 375793.00,
                'hitos_pago'                => "20% Anticipo\n20% Contra firma de planos de ingeniería\n20% Contra entrega de avances de la semana 8 de fabricación\n20% Contra aviso de entrega al sitio de entrega\n20% Crédito a 30 días, después de entregado el separador en sitio",
                'responsable'               => 'Guadalupe Osorio',
                'archivo_oferta'            => '260205-0-IGC-P&C x _Separador Horizontal de Gas de Desfogue.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => null,          // N/A en CSV
                'cliente_alias'             => 'SAR',
                'contacto'                  => 'Moises Villareal',
                'datos_contacto'            => "Correo: moises.villarreal@sarreal.com.mx",
                'lugar'                     => 'Tabasco',
                'alcance'                   => 'Servicio de Drilling de 2" en ducto principal en accesorio niple tipo cosasco',
                'tech_reference'            => '260209-0-SAR-HTP 2x2 _Drillings 2" Niple COSASCO Sarreal',
                'fecha_envio'               => '2026-02-11',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 44615.38,
                'hitos_pago'                => "50% Anticipo\n50% Concluyendo trabajos",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260209-0-SAR-HTP 2x2 _Drillings 2 Niple COSASCO Sarreal.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => '011/26',
                'cliente_alias'             => 'ARS',
                'contacto'                  => 'Emilio Morán',
                'datos_contacto'            => "Correo: emilio.moran@arseal.com.mx",
                'lugar'                     => 'Guanajuato',
                'alcance'                   => 'Suministro Válvulas bola Trunnion 8" y 10" 600#',
                'tech_reference'            => '260211-0-ARS-VLV 10x8 _Propuesta Suministro Válvulas bola Trunnion 8" y10" 600#',
                'fecha_envio'               => '2026-02-11',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 68542.02,
                'hitos_pago'                => "50% Anticipo\n50% Concluyendo trabajos",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260211-0-ARS-VLV 10x8 _Propuesta Suministro Válvulas bola Trunnion 8 y10 600.pdf',
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => '012/26',
                'cliente_alias'             => 'ESE',
                'contacto'                  => 'Mario Cervantes',
                'datos_contacto'            => "Correo: mcervantes@esentia-energy.com",
                'lugar'                     => 'Guadalajara',
                'alcance'                   => 'Servicio DLS 36" 600# Recuperación Diablo, Gasoducto Villa de Reyes',
                'tech_reference'            => '260216-0-FER-DLSS 36x _Servicio DLS 36" 600# Recuperación Diablo, Gasoducto Villa de Reyes-Guadalajara',
                'fecha_envio'               => '2026-02-18',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 1260000.00,
                'hitos_pago'                => "40% Anticipo\n40% Contra soldadura de silletas\n20% Concluyendo la terminación de los Trabajos",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260216-0-FER-DLSS 36x _Servicio DLS 36 600# Recuperación Diablo, Gasoducto Villa de Reyes-Guadalajara.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => '013/26',
                'cliente_alias'             => 'ESE',
                'contacto'                  => 'Israel Hernández',
                'datos_contacto'            => "Teléfono: 55 7901 8338\nCorreo: ihernandez@esentia-energy.com",
                'lugar'                     => 'Chihuahua',
                'alcance'                   => 'Servicios Hot Tap 8" y 2" GCC-Samalayuca',
                'tech_reference'            => '260219-0-FER-HTP 36x8 _Servicios Hot Tap 8" y 2" GCC-Samalayuca',
                'fecha_envio'               => '2026-02-19',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 63191.20,
                'hitos_pago'                => "50% Anticipo\n50% Concluyendo trabajos",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260219-0-FER-HTP 36x8 _Servicios Hot Tap 8 y 2 GCC-Samalayuca.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => null,          // Sin CP en CSV (SEDENA Frente 10)
                'cliente_alias'             => 'SDN',
                'contacto'                  => null,
                'datos_contacto'            => null,
                'lugar'                     => 'Queretaro',
                'alcance'                   => "Servicios integrales de obra — Mecánica de desvío de ducto de 24\" (Frente 10) Tren México–Querétaro",
                'tech_reference'            => '260216-SDN-HTSF 24x frente 10',
                'fecha_envio'               => '2026-02-16',
                'fecha_modificacion_oferta' => '2026-02-19',
                'monto_usd'                 => 9403052.35,
                'hitos_pago'                => "40% Anticipo\n20% A la fabricación y procura de fittings\n20% A la procura de tubería en sitio\n10% A la conclusión de las perforaciones\n10% Al retiro de tubería existente",
                'responsable'               => 'Aquiles Garcia',
                'archivo_oferta'            => '260216-DESVIO 24 IN - FRENTE 10 - SEDENA Rev1.pdf',
                'ponderacion'               => 75,
            ],
            [
                'cp_numero'                 => null,          // Sin CP en CSV (SEDENA Frente 11)
                'cliente_alias'             => 'SDN',
                'contacto'                  => null,
                'datos_contacto'            => null,
                'lugar'                     => 'Queretaro',
                'alcance'                   => "Servicios integrales de obra — Mecánica de desvío de ducto de 24\" (Frente 11) Tren México–Querétaro",
                'tech_reference'            => '260220-SDN-HTSF 24x frente 11',
                'fecha_envio'               => '2026-02-20',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 15078457.65,
                'hitos_pago'                => "40% Anticipo\n20% A la fabricación y procura de fittings\n20% A la procura de tubería en sitio\n10% A la conclusión de las perforaciones\n10% Al retiro de tubería existente",
                'responsable'               => 'Aquiles Garcia',
                'archivo_oferta'            => '260220-DESVIOS 24 IN - FRENTE 11 - SEDENA.pdf',
                'ponderacion'               => 75,
            ],
            [
                'cp_numero'                 => '150/25',
                'cliente_alias'             => 'TCE',
                'contacto'                  => 'Alvaro Vallejo',
                'datos_contacto'            => "Correo: edith_yanez_ramirez@tcenergy.com",
                'lugar'                     => 'Tabasco',
                'alcance'                   => 'Suministros a partes de repuesto a VBT Dos Bocas',
                'tech_reference'            => '251009-0-TCE-VBT VRSx _Partes de repuesto a VBT Dos Bocas',
                'fecha_envio'               => '2025-10-30',
                'fecha_modificacion_oferta' => '2026-02-24',
                'monto_usd'                 => 59602.72,
                'hitos_pago'                => '100% Contra entrega de refacciones (Pago a 30 días después de entrega)',
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '251009-0-TCE-VBT VRSx _Partes de repuesto a VBT Dos Bocas Rev.2.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => '014/26',
                'cliente_alias'             => 'IGA',
                'contacto'                  => 'Sandra Edith',
                'datos_contacto'            => "Correo: srenedo@igasamex.com.mx",
                'lugar'                     => 'Queretaro',
                'alcance'                   => 'Revisión empate Biseles válvula-niple 6" 600# para proyecto Keken 16\'x6\'',
                'tech_reference'            => '260225-0-IGA-OTH 6x _Revisión empate Biseles válvula-niple 6"',
                'fecha_envio'               => '2026-02-25',
                'fecha_modificacion_oferta' => '2026-03-05',
                'monto_usd'                 => 1400.00,
                'hitos_pago'                => '100% (una vez se comparta la OC se considerará 15 días para realizar el pago correspondiente)',
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260225-0-IGA-OTH 6x _Revisión empate Biseles válvula-niple 6_Rev.2.pdf',
                'ponderacion'               => 75,
            ],
            [
                'cp_numero'                 => '016-B/26',    // Duplicado CP 016/26 en CSV — segundo registro (IGASAMEX-Luis Antonio)
                'cliente_alias'             => 'IGA',
                'contacto'                  => 'Luis Antonio',
                'datos_contacto'            => "Correo: lescamilla@igasamex.com.mx",
                'lugar'                     => 'Edo. Mexico',
                'alcance'                   => 'Servicio PH VBT 4" 300# Atlacomulco',
                'tech_reference'            => '260303-0-IGA-VLV 4x _Servicio PH VBT 4" 300# Atlacomulco',
                'fecha_envio'               => '2026-03-03',
                'fecha_modificacion_oferta' => '2026-03-05',
                'monto_usd'                 => 7431.20,
                'hitos_pago'                => '100% Al Terminar PH',
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '251009-0-TCE-VBT VRSx _Partes de repuesto a VBT Dos Bocas Rev.3.pdf',
                'ponderacion'               => 100,
            ],
            [
                'cp_numero'                 => null,          // Sin CP en CSV
                'cliente_alias'             => 'ENG',
                'contacto'                  => 'Berenice',
                'datos_contacto'            => "Correo: berenice.hernandez_eleno@engie.com",
                'lugar'                     => 'Guanajuato',
                'alcance'                   => 'Interconexión Meprosa HT 16"X6" Salamanca Guanajuato',
                'tech_reference'            => '241129-0-ENG-HTS 16x6 _Interconexion 16"x6" 600# Meprosa',
                'fecha_envio'               => '2026-02-09',
                'fecha_modificacion_oferta' => '2026-03-10',
                'monto_usd'                 => 352715.79,
                'hitos_pago'                => "30% Anticipo\n20% Contra Entrega de Accesorios\n20% Finalizando Encapsulado\n30% Finalizando Trabajos",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '241129-0-ENG-HTS 16x6 _Interconexion 16x6 600# Meprosa Rev.1.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => null,
                'cliente_alias'             => 'G3V',
                'contacto'                  => 'Héctor Dionisio',
                'datos_contacto'            => "Correo: hector.dionisio@3vta.com",
                'lugar'                     => 'Tabasco',
                'alcance'                   => 'Suministro de Válvulas de 24" 600# RF',
                'tech_reference'            => '260305-0-G3V-VLV x _Suministro de Válvula de 24" 600# RF',
                'fecha_envio'               => '2026-03-10',
                'fecha_modificacion_oferta' => '2026-03-10',
                'monto_usd'                 => 223440.56,
                'hitos_pago'                => '100% Anticipo',
                'responsable'               => null,
                'archivo_oferta'            => '260305-0-G3V-VLV x _Suministro de Válvula de 24 600# RF',
                'ponderacion'               => 10,
            ],
            [
                'cp_numero'                 => null,
                'cliente_alias'             => 'IGC',
                'contacto'                  => 'Balam Hernandez',
                'datos_contacto'            => "Correo: balanhernandez@indheca.com",
                'lugar'                     => 'Tabasco',
                'alcance'                   => 'Suministro de Tubería de AC 24" extremos biselados',
                'tech_reference'            => '260309-0-IGC-P&C x _Suministro de Tubería A.C. 24',
                'fecha_envio'               => '2026-03-10',
                'fecha_modificacion_oferta' => '2026-03-10',
                'monto_usd'                 => 1274125.00,
                'hitos_pago'                => "50% Anticipo\n50% Crédito a 30 días",
                'responsable'               => null,
                'archivo_oferta'            => '260309-0-IGC-P&C x _Suministro de Tubería A.C. 24',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => null,
                'cliente_alias'             => 'GSO',
                'contacto'                  => 'Juan Pablo Zavala',
                'datos_contacto'            => "Correo: Juan.zavala@geolis.mx",
                'lugar'                     => 'Tabasco',
                'alcance'                   => 'Servicio de Hot Tapping Integral 16" x 12" Clase 600# RF',
                'tech_reference'            => '260311-0-GSO-HTP x _Hot Tapping Integral 16x12 600# RF',
                'fecha_envio'               => '2026-03-11',
                'fecha_modificacion_oferta' => '2026-03-11',
                'monto_usd'                 => 147279.40,
                'hitos_pago'                => "50% Anticipo\n30% Contra Aviso de movilización\n20% Finalizar Perforación en Sitio",
                'responsable'               => 'Guadalupe Osorio',
                'archivo_oferta'            => '260311-0-GSO-HTP x _Hot Tapping Integral 16x12 600# RF',
                'ponderacion'               => 75,
            ],
            [
                'cp_numero'                 => null,
                'cliente_alias'             => 'SAR',
                'contacto'                  => 'Moises Villareal',
                'datos_contacto'            => "Correo: moises.villarreal@sarreal.com.mx",
                'lugar'                     => 'Tabasco',
                'alcance'                   => 'Suministro de Válvulas 4", 8" y 20" 900#',
                'tech_reference'            => '260310-0-SAR-VLV x _Suministro de Válvulas 4, 8 y 20 900# RTJ',
                'fecha_envio'               => '2026-03-12',
                'fecha_modificacion_oferta' => '2026-03-12',
                'monto_usd'                 => 524422.96,
                'hitos_pago'                => '100% Anticipo',
                'responsable'               => 'Guadalupe Osorio',
                'archivo_oferta'            => '260310-0-SAR-VLV x _Suministro de Válvulas 4, 8 y 20 900# RTJ',
                'ponderacion'               => 75,
            ],
            [
                'cp_numero'                 => '022/26',
                'cliente_alias'             => 'PIF',
                'contacto'                  => 'Mercedes Guadalupe Sánchez Sánchez',
                'datos_contacto'            => "Correo: csanchez@pifusa.mx",
                'lugar'                     => 'San Luis Potosi',
                'alcance'                   => 'Suministros Juntas aislantes en Estación de Compresión VDR para PIFUSA',
                'tech_reference'            => '260410-0-PIF-OTHRS 6x _Suminstro_Juntas Aislantes',
                'fecha_envio'               => '2026-04-10',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 23527.43,
                'hitos_pago'                => "50% Anticipo\n50% Contra entrega de material",
                'responsable'               => 'Fernando Basave',
                'archivo_oferta'            => '260410-0-PIF-OTHRS 6x _Suminstro_Juntas Aislantes.pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => 'CP-021/26',
                'cliente_alias'             => 'COC',
                'contacto'                  => 'Antonio',
                'datos_contacto'            => "Teléfono: 9932857407\nCorreo: procura@grupococomex.com",
                'lugar'                     => 'Veracruz',
                'alcance'                   => "Suministro de accesorio Hot Tap Fitting, VBT 8\" 600# RF, Soldadura en Línea Viva, PNDs, Hot Tapping y Torque",
                'tech_reference'            => '260423-0-COC-HTP_8x8_Veracruz',
                'fecha_envio'               => '2026-04-23',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 70125.00,
                'hitos_pago'                => "50% Anticipo\n50% Contra aviso de movilización",
                'responsable'               => 'Sergio Ordaz',
                'archivo_oferta'            => '260423-0-COC-HTP_8x8_Veracruz (1).pdf',
                'ponderacion'               => 25,
            ],
            [
                'cp_numero'                 => 'CP-027/26',
                'cliente_alias'             => 'ME',
                'contacto'                  => 'Victor Martinez',
                'datos_contacto'            => "Teléfono: 4626254968\nCorreo: vmartinez@marabis.com",
                'lugar'                     => 'Guanajuato',
                'alcance'                   => 'Suministro de una válvula trunnion de paso completo en acero al carbono API 6D de 14" 300# RF y una válvula trunnion de paso completo en acero al carbono API 6D de 8" 600# RF',
                'tech_reference'            => '260426-0-ME-SUMINISTRO VBT 14 300# RF y 8 600# RF',
                'fecha_envio'               => '2026-05-06',
                'fecha_modificacion_oferta' => null,
                'monto_usd'                 => 31409.47,
                'hitos_pago'                => "50% Anticipo\n50% Contra entrega de válvulas",
                'responsable'               => 'Sergio Ordaz',
                'archivo_oferta'            => '260426-0-ME-SUMINISTRO VBT 14 300# RF y 8 600# RF.pdf',
                'ponderacion'               => 25,
            ],
        ];

        // ── Inserción ──────────────────────────────────────────────────────────────
        foreach ($ofertas as $data) {
            $clienteId = $cli($data['cliente_alias']);
            if (! $clienteId) {
                $this->command->warn("Cliente no encontrado: {$data['cliente_alias']} — registro omitido.");
                continue;
            }

            Proyecto::create([
                'cp_numero'                 => $data['cp_numero'],
                'cliente_id'                => $clienteId,
                'contacto'                  => $data['contacto'],
                'datos_contacto'            => $data['datos_contacto'],
                'lugar_id'                  => $lug($data['lugar']),
                'alcance'                   => $data['alcance'],
                'tech_reference'            => $data['tech_reference'],
                'fecha_envio'               => $data['fecha_envio'],
                'fecha_modificacion_oferta' => $data['fecha_modificacion_oferta'],
                'monto_usd'                 => $data['monto_usd'],
                'hitos_pago'                => $data['hitos_pago'],
                'elaboro_id'                => $usr($data['responsable']),
                'estado'                    => 'presentado',   // STATUS = ENVIADO en el CSV
                'archivo_oferta'            => $data['archivo_oferta'],
                'ponderacion'               => $data['ponderacion'],
                'anio'                      => (int) substr($data['fecha_envio'], 0, 4),
            ]);
        }

        $this->command->info('Ofertas2026Seeder: ' . count($ofertas) . ' registros procesados.');
    }
}
